spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/devarena}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:YOUR_LOCAL_POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      url: ${REDIS_URL:redis://localhost:6379}

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET:f1statsexplorersecretkey12345678901234567890}

admin:
  secret-key: ${ADMIN_SECRET_KEY:devArena@Admin#2026}