spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      url: ${REDIS_URL}

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET}

admin:
  secret-key: ${ADMIN_SECRET_KEY}